spring.application.name=Ecommerce Backend
#Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


server.port=${PORT}

BASE_URL=${FAKESTORE_API_URL}
fakeStore.category.url=${FAKESTORE_API_URL}/products/categories
fakeStore.productsByCategory.url=${FAKESTORE_API_URL}/products/category

